export  const GET_ALL_QUESTIONS="GET_ALL_QUESTIONS";
export  const GET_CURRENT_QUESTION="GET_CURRENT_QUESTION";
export  const GET_SCORE="GET_SCORE";
export  const GET_CORRECT="GET_CORRECT";
export  const GET_INCORRECT="GET_INCORRECT";
export  const GET_CORRECT_COUNT="GET_CORRECT_COUNT";
export  const GET_INCORRECT_COUNT="GET_INCORRECT_COUNT";

